import type { Creature } from './models';
import { RARITY } from './models';

export const MOCK_CREATURES: Creature[] = [
  {
    id: 'slime_knight',
    name: 'Slime Knight',
    role: 'Tank',
    rarity: RARITY.COMMON,
    stats: { hp: 1200, atk: 50, spd: 0.8 },
    synergies: ['Gelatinous', 'Knight'],
    imageUrl: 'https://picsum.photos/100/100?random=1',
  },
  {
    id: 'ember_fox',
    name: 'Ember Fox',
    role: 'DPS',
    rarity: RARITY.RARE,
    stats: { hp: 600, atk: 180, spd: 1.4 },
    synergies: ['Beast', 'Fire'],
    imageUrl: 'https://picsum.photos/100/100?random=2',
  },
  {
    id: 'clockwork_golem',
    name: 'Clockwork Golem',
    role: 'Tank',
    rarity: RARITY.EPIC,
    stats: { hp: 2000, atk: 80, spd: 0.5 },
    synergies: ['Mech', 'Heavy'],
    imageUrl: 'https://picsum.photos/100/100?random=3',
  },
  {
    id: 'crystal_weaver',
    name: 'Crystal Weaver',
    role: 'Support',
    rarity: RARITY.LEGENDARY,
    stats: { hp: 900, atk: 110, spd: 1.0 },
    synergies: ['Crystal', 'Mystic'],
    imageUrl: 'https://picsum.photos/100/100?random=5',
  },
  {
    id: 'field_medic',
    name: 'Field Medic',
    role: 'Support',
    rarity: RARITY.RARE,
    stats: { hp: 850, atk: 90, spd: 1.1 },
    synergies: ['Medic', 'Mystic'],
    imageUrl: 'https://picsum.photos/100/100?random=6',
  },
  {
    id: 'iron_striker',
    name: 'Iron Striker',
    role: 'DPS',
    rarity: RARITY.EPIC,
    stats: { hp: 900, atk: 140, spd: 1.3 },
    synergies: ['Mech', 'Knight'],
    imageUrl: 'https://picsum.photos/100/100?random=7',
  },
  {
    id: 'thornback_boar',
    name: 'Thornback Boar',
    role: 'Tank',
    rarity: RARITY.RARE,
    stats: { hp: 1500, atk: 75, spd: 0.8 },
    synergies: ['Vine', 'Beast'],
    imageUrl: 'https://picsum.photos/100/100?random=8',
  },
  {
    id: 'mist_sage',
    name: 'Mist Sage',
    role: 'Support',
    rarity: RARITY.EPIC,
    stats: { hp: 950, atk: 105, spd: 0.9 },
    synergies: ['Mist', 'Mystic'],
    imageUrl: 'https://picsum.photos/100/100?random=9',
  },
  {
    id: 'storm_hawk',
    name: 'Storm Hawk',
    role: 'DPS',
    rarity: RARITY.RARE,
    stats: { hp: 650, atk: 165, spd: 1.3 },
    synergies: ['Storm', 'Beast'],
    imageUrl: 'https://picsum.photos/100/100?random=10',
  },
  {
    id: 'sun_paladin',
    name: 'Sun Paladin',
    role: 'Tank',
    rarity: RARITY.LEGENDARY,
    stats: { hp: 1700, atk: 95, spd: 0.7 },
    synergies: ['Knight', 'Fire'],
    imageUrl: 'https://picsum.photos/100/100?random=11',
  },
  {
    id: 'void_wisp',
    name: 'Void Wisp',
    role: 'DPS',
    rarity: RARITY.EPIC,
    stats: { hp: 520, atk: 210, spd: 1.1 },
    synergies: ['Void', 'Mystic'],
    imageUrl: 'https://picsum.photos/100/100?random=12',
  },
  {
    id: 'scrap_artificer',
    name: 'Scrap Artificer',
    role: 'Support',
    rarity: RARITY.RARE,
    stats: { hp: 820, atk: 95, spd: 1.0 },
    synergies: ['Scrap', 'Mech'],
    imageUrl: 'https://picsum.photos/100/100?random=13',
  },
];

export const PATCH_NOTES = [
  { version: 'v1.2.4', date: 'Today', title: 'Slime Synergy Buff' },
  { version: 'v1.2.3', date: '2 days ago', title: 'Fixed training budget glitch' },
];
